// File generated by FlutterFire CLI.
// Contains Firebase configuration options for your app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwZWpqLQLizT9b6hKcuucAiylXgq9actQ',
    appId: '1:702431682405:web:b80f68ec981fe60bd1cb8c',
    messagingSenderId: '702431682405',
    projectId: 'myapp-6ed81',
    authDomain: 'myapp-6ed81.firebaseapp.com',
    storageBucket: 'myapp-6ed81.firebasestorage.app',
    measurementId: 'G-XWZL0LBZPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwZWpqLQLizT9b6hKcuucAiylXgq9actQ',
    appId: '1:702431682405:android:b80f68ec981fe60bd1cb8c',
    messagingSenderId: '702431682405',
    projectId: 'myapp-6ed81',
    storageBucket: 'myapp-6ed81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Itz5d54wdjP03VLCrnE9DF5-5Tm2rRk',
    appId: '1:702431682405:ios:df3ce1f72f9fc99bd1cb8c',
    messagingSenderId: '702431682405',
    projectId: 'myapp-6ed81',
    storageBucket: 'myapp-6ed81.firebasestorage.app',
    iosClientId: '702431682405-g9ou4mhiil4gj2fte8g3jlr2voelkd2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Itz5d54wdjP03VLCrnE9DF5-5Tm2rRk',
    appId: '1:702431682405:macos:1234567890abcdef',
    messagingSenderId: '702431682405',
    projectId: 'myapp-6ed81',
    storageBucket: 'myapp-6ed81.firebasestorage.app',
    iosClientId: '702431682405-iosmacos.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwZWpqLQLizT9b6hKcuucAiylXgq9actQ',
    appId: '1:702431682405:windows:1234567890abcdef',
    messagingSenderId: '702431682405',
    projectId: 'myapp-6ed81',
    storageBucket: 'myapp-6ed81.firebasestorage.app',
  );
}